# ?????
server.port=8080

# ?????
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT??
jwt.secret=SFDFSDDF
jwt.expiration=86400000

# ???OSS??
aliyun.oss.endpoint=oss-cn-hangzhou.aliyuncs.com
aliyun.oss.access-key-id=your-access-key-id
aliyun.oss.access-key-secret=your-access-key-secret
aliyun.oss.bucket-name=your-bucket-name

